Repository remoteintech/remote-jobs, pull requests merged in 2020-10, with the labels that each got.

#830 Adds Pathable information. #639
  README.md
  company-profiles/pathable.md
Labels: author-reply-needed

#828 Update linux-foundation.md
  README.md
  company-profiles/linux-foundation.md
Labels: author-reply-needed

#816 Issue 639
  README.md
  company-profiles/black-pixel.md
  company-profiles/hypergiant.md
Labels: author-reply-needed

#838 add Vercel.
  README.md
  company-profiles/vercel.md
Labels: author-reply-needed

#877 Update signeasy.md
  README.md
  company-profiles/signeasy.md
Labels: author-reply-needed

#894 Updated stitch-fix.md
  README.md
  company-profiles/stitch-fix.md
Labels: author-reply-needed

#904 Add Molteo company
  README.md
  company-profiles/molteo.md
Labels: author-reply-needed

#919 I added On the go systems company
  README.md
  company-profiles/buysellads.md
  company-profiles/on-the-go-systems.md
Labels: author-reply-needed

#960 Update upworthy.md
  README.md
  company-profiles/upworthy.md
Labels: author-reply-needed, in progress

#968 Update sweetrush.md
  README.md
  company-profiles/delighted.md
  company-profiles/sweetrush.md
Labels: author-reply-needed, in progress

#973 Updating Upworthy and Intevity (twin technologies)
  README.md
  company-profiles/intevity.md
  company-profiles/twin-technologies.md
  company-profiles/upworthy.md
  package-lock.json
  package.json
Labels: author-reply-needed

#990 Adding Hopper to list
  README.md
  company-profiles/Mozzila.md
  company-profiles/hopper.md
Labels: author-reply-needed, in progress

#1007 Detail suse profile
  README.md
  company-profiles/suse.md
Labels: author-reply-needed

#1026 Updated teleport.md
  README.md
  company-profiles/teleport.md
Labels: awaiting-checks

#1028 Update uptrending.md
  README.md
  company-profiles/husl-digital.md
  company-profiles/uptrending.md
Labels: awaiting-checks

#1030 Updated salesforce file with new information
  README.md
  company-profiles/salesforce.md
Labels: awaiting-checks

#1038 Adds Flowing
  README.md
  company-profiles/flowing.md
Labels: awaiting-checks

#1068 Fix this
  PULL_REQUEST_TEMPLATE.MD
  README.md
  company-profiles/got-soccer.md
  company-profiles/gotsoccer-llc.md
Labels: awaiting-checks

#1046 added a new company profile called skyrocket ventures
  README.md
  company-profiles/skyrocket-ventures.md
Labels: awaiting-checks

#1077 add new company - VIPERdev
  README.md
  company-profiles/viperdev.md
Labels: awaiting-checks
