Repository remoteintech/remote-jobs, pull requests merged in 2022-10, with the labels that each got.

#1439 Uncomment username from FUNDING.yml
  .github/FUNDING.yml
Labels: housekeeping

#1438 chore: Move Community Health Files
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.MD
  README.md
Labels: housekeeping

#1289 Editing "Mycelium" company information
  README.md
  company-profiles/mycelium.md
Labels: hacktoberfest-accepted, awaiting-checks

#1433 Add New Company - ImagineLearning
  .gitignore
  README.md
  company-profiles/imagine-learning.md
Labels: author-reply-needed

#1449 fix: Added Some Missing Info
  company-profiles/bright-funds.md
  company-profiles/britecore.md
  company-profiles/featurist.md
Labels: rtm

#1451 add new company - Sigma Defense
  README.md
  company-profiles/sigma-defense.md
Labels: rtm

#1452 Add new company - Devsquad
  README.md
  company-profiles/devsquad.md
Labels: rtm

#1453 Add New Company - EatStreet
  README.md
  company-profiles/eatstreet.md
Labels: rtm

#1454 edit Harvest company
  company-profiles/harvest.md
Labels: rtm

#1458 Add new company - LIGHTSPEED POS
  README.md
  company-profiles/lightspeed.md
Labels: rtm

#1470 [Edit Hypergiant] Update careers link
  company-profiles/hypergiant.md
Labels: rtm

#1475 [Add new company -Digitise]
  README.md
  company-profiles/digitise.md
Labels: rtm

#1440 Added Nagarro into this
  README.md
  company-profiles/nagarro.md
Labels: author-reply-needed

#1444 Add new company - GFT
  README.md
  company-profiles/gft.md
Labels: author-reply-needed

#1466 add new company - Coingape
  README.md
  company-profiles/coingape.md
Labels: author-reply-needed

#1423 Add Annertech.com company profile.
  README.md
  company-profiles/annertech.md
Labels: author-reply-needed

#1490 Add meteorops
  README.md
  company-profiles/meteorops.md
Labels: rtm

#1500 Housekeeping - update CoC version and PR template
  .github/CODE_OF_CONDUCT.md
  .github/PULL_REQUEST_TEMPLATE.MD
Labels: housekeeping

#1468 Update 17hats.md
  company-profiles/17hats.md
Labels: rtm

#1478 Remove "Big Wheel Brigade"
  README.md
  company-profiles/big-wheel-brigade.md
Labels: rtm

#1482 updated remote work location of Wells fargo & Sysdig
  README.md
Labels: rtm

#1492 Added Atlassian
  README.md
  company-profiles/atlassian.md
Labels: rtm

#1504 Add new company - Granicus
  README.md
  company-profiles/granicus.md
Labels: rtm

#1502 Add new company - CODE LIKE A GIRL
  README.md
  company-profiles/code-like-a-girl.md
Labels: rtm

#1498 Adding new company - CANCOM
  README.md
  company-profiles/cancom.md
Labels: rtm

#1518 feat: Added New Company - Dropbox
  README.md
  company-profiles/dropbox.md
Labels: rtm

#1519 Added inshorts.md as a remote company
  README.md
  company-profiles/inshorts.md
Labels: rtm

#1520 Adding New Company - MeridianLink
  README.md
  company-profiles/meridianlink.md
Labels: rtm

#1512 [Add new company-Clootrack]
  README.md
  company-profiles/clootrack.md
Labels: rtm

#1522 Add new company - Applaudo
  README.md
  company-profiles/applaudo.md
Labels: rtm

#1523 Add New Company - Instructure
  README.md
  company-profiles/instructure.md
Labels: rtm

#1528 Add new company - Edgio
  README.md
  company-profiles/edgio.md
Labels: rtm

#1535 Added Nvidia Company
  README.md
  company-profiles/nvidia.md
Labels: rtm

#1542 add new company - Alami
  README.md
  company-profiles/alami.md
Labels: rtm

#1543 Edit FactorialHR
  company-profiles/factorialhr.md
Labels: rtm

#1521 add new company - Ocient
  README.md
  company-profiles/ocient.md
Labels: rtm

#1548 Broken link fixes Part 1
  README.md
  company-profiles/adaface.md
  company-profiles/canonical.md
  company-profiles/colivre.md
  company-profiles/focusnetworks.md
  company-profiles/gorman-health-group.md
  company-profiles/mapbox.md
  company-profiles/stairlin.md
  company-profiles/teamultra.md
Labels: rtm

#1544 Add New Company - Aerostrat
  README.md
  company-profiles/aerostrat.md
Labels: awaiting-maintainer-approval

#1526 Add new company - "Fly.io"
  README.md
  company-profiles/fly-io.md
Labels: awaiting-maintainer-approval

#1541 Add new company - Fiverr
  README.md
  company-profiles/fiverr.md
Labels: awaiting-maintainer-approval

#1546 add new company - Primer
  README.md
  company-profiles/primer.md
Labels: awaiting-maintainer-approval

#1552 added GoDaddy company
  README.md
  company-profiles/godaddy.md
Labels: awaiting-maintainer-approval

#1553 Added new company - Bounteous
  README.md
  company-profiles/bounteous.md
Labels: awaiting-maintainer-approval

#1554 Add new company - Data Science Dojo
  README.md
  company-profiles/data-science-dojo.md
Labels: awaiting-maintainer-approval

#1556 Add new company - Teravision Technologies
  README.md
  company-profiles/teravision-technologies.md
Labels: awaiting-maintainer-approval

#1551 Added new company - Prisma
  README.md
  company-profiles/prisma.md
Labels: awaiting-maintainer-approval

#1524 add new company - ADEVA
  README.md
  company-profiles/adeva.md
Labels: awaiting-checks

#1525 Add new company - Beyond Company
  README.md
  company-profiles/beyond-company.md
Labels: awaiting-checks

#1539 Add new company - coodesh
  README.md
  company-profiles/coodesh.md
Labels: awaiting-checks

#1545 Adding Ordermentum
  README.md
  company-profiles/ordermentum.md
Labels: awaiting-checks

#1547 add new company - CWT
  README.md
  company-profiles/cwt.md
Labels: awaiting-checks

#1448 add new company - Mindful
  README.md
  company-profiles/mindful.md
Labels: awaiting-checks

#1559 add new company - Virta Health
  README.md
  company-profiles/virta-health.md
Labels: awaiting-checks

#1571 add new company - Smmile Digital
  README.md
  company-profiles/smmile-digital.md
Labels: author-reply-needed

#1462 Ten
  README.md
  company-profiles/vmware.md
Labels: rtm

#1505 fix: An Ungodly Ammount of Typos
  company-profiles/annertech.md
  company-profiles/axelerant.md
  company-profiles/axios.md
  company-profiles/bairesdev.md
  company-profiles/bebanjo.md
  company-profiles/betable.md
  company-profiles/blameless.md
  company-profiles/bluespark.md
  company-profiles/carbon-black.md
  company-profiles/core-apps.md
  company-profiles/cyber-whale.md
  company-profiles/digitise.md
  company-profiles/duckduckgo.md
  company-profiles/evelo.md
  company-profiles/ffw-agency.md
  company-profiles/findify.md
  company-profiles/fire-engine-red.md
  company-profiles/fireball-labs.md
  company-profiles/flowing.md
  company-profiles/fraudio.md
  company-profiles/fuel-made.md
  company-profiles/gft.md
  company-profiles/gitlab.md
  company-profiles/gojob.md
  company-profiles/he-labs.md
  company-profiles/headway.md
  company-profiles/husl-digital.md
  company-profiles/iclinic.md
  company-profiles/instamobile.md
  company-profiles/intellum.md
  company-profiles/interpersonal-frequency-i-f.md
  company-profiles/iohk.md
  company-profiles/joyent.md
  company-profiles/laterpay.md
  company-profiles/leadership-success.md
  company-profiles/mtc.md
  company-profiles/platform-sh.md
  company-profiles/recurly.md
  company-profiles/shogun.md
  company-profiles/yandex.md
Labels: rtm

#1549 [ADD] New job entry (Chess.com)
  README.md
  company-profiles/chess.md
Labels: rtm

#1563 add new company - Brainstorm Force
  README.md
  company-profiles/brainstorm-force.md
Labels: rtm

#1564 [ADD] Entry job LeadIQ
  README.md
  company-profiles/leadiq.md
Labels: rtm

#1566 Add new company - Replit
  README.md
  company-profiles/replit.md
Labels: rtm

#1567 feat: Add Safeguard-Global
  README.md
  company-profiles/safeguard-global.md
Labels: rtm

#1568 Add new company - Mayvue Solutions
  README.md
  company-profiles/mayvue.md
Labels: rtm

#1575 add new company - Coalition technologies
  README.md
  company-profiles/coalition-technologies.md
Labels: rtm

#1580 Add new company - Brikl
  README.md
  company-profiles/brikl.md
Labels: rtm
