Repository remoteintech/remote-jobs, pull requests merged in 2022-11, with the labels that each got.

#1591 Create kinsta.md
  README.md
  company-profiles/kinsta.md
Labels: awaiting-maintainer-approval

#1583 Intuit Inc.
  README.md
  company-profiles/intuit.md
Labels: hacktoberfest-accepted, rtm

#1584 feat: Add Rakuten Travel Xchange
  README.md
  company-profiles/rakuten-travel-xchange.md
Labels: rtm

#1585 feat: Add Massive Pixel Creation
  README.md
  company-profiles/massive-pixel-creation.md
Labels: hacktoberfest-accepted, rtm

#1586 edit Shippabo company: update job listing url
  company-profiles/shippabo.md
Labels: hacktoberfest-accepted, rtm

#1587 Added Gerencianet - Brazil
  README.md
  company-profiles/gerencianet.md
Labels: hacktoberfest-accepted, rtm

#1588 HashEx company
  README.md
  company-profiles/hashex.md
Labels: hacktoberfest-accepted, rtm
