Repository remoteintech/remote-jobs, pull requests merged in 2023-11, with the labels that each got.

#1756 Remove Acct #1738
  README.md
  company-profiles/acct.md
Labels: author-reply-needed, housekeeping

#1717 Adding FIS global
  README.md
  company-profiles/fis-global.md
Labels: addition, awaiting-checks

#1733 Added new company Extreme Networks
  README.md
  company-profiles/extreme-networks.md
Labels: addition, awaiting-checks

#1735 add new company - Launch Potato
  README.md
  company-profiles/launch-potato.md
Labels: addition, awaiting-checks

#1732 Added new company Ebury
  README.md
  company-profiles/ebury.md
Labels: addition

#1681 add new company - Zootools
  README.md
  company-profiles/zootools.md
Labels: addition, awaiting-checks

#1699 Added company #1638
  README.md
  company-profiles/vivo.md
Labels: addition, awaiting-checks

#1715 added company Embraer
  README.md
  company-profiles/embraer.md
Labels: addition, awaiting-checks

#1734 add new company - Picpay
  README.md
  company-profiles/picpay.md
Labels: addition, awaiting-checks

#1684 add new company - IStem
  README.md
  company-profiles/i-stem.md
Labels: addition
