Repository remoteintech/remote-jobs, pull requests merged in 2023-08, with the labels that each got.

#1632 Add Cards Against Humanity Careers page link
  company-profiles/cards-against-humanity.md
Labels: addition

#1484 Added SadaPay
  README.md
  company-profiles/sadapay.md
Labels: addition, author-reply-needed

#1474 The Planet Company is added
  README.md
  company-profiles/the-planet-group.md
Labels: addition, author-reply-needed, awaiting-checks

#1550 Added new company - Parexel
  README.md
  company-profiles/parexel.md
Labels: addition

#1599 Added new Career Page in Aula.md
  company-profiles/aula.md
Labels: housekeeping

#1600 Updated Carrer Page in Argyle
  company-profiles/argyle.md
Labels: housekeeping

#1601 Updated bitrecore Career Page Link
  company-profiles/britecore.md
Labels: housekeeping, awaiting-maintainer-approval

#1602 Add new company - Revolgy
  README.md
  company-profiles/revolgy.md
Labels: addition

#1605 Update Airbank to Friday Finance
  README.md
  company-profiles/airbank.md
  company-profiles/friday-finance.md
Labels: housekeeping
