Repository remoteintech/remote-jobs, pull requests merged in 2023-10, with the labels that each got.

#1622 Added Shattered Silicon database consultancy company.
  README.md
  company-profiles/shattered-silicon.md
Labels: addition, author-reply-needed

#1655 Add new company - Yahoo!
  README.md
  company-profiles/yahoo.md
Labels: addition

#1657 add new company - Accor
  README.md
  company-profiles/accor.md
Labels: addition, rtm

#1649 Edit Aha.io Company
  README.md
  company-profiles/aha.md
Labels: housekeeping, awaiting-checks

#1673 UPDATE: 404.html
  site/templates/404.html
Labels: enhancement, awaiting-maintainer-approval

#1656 add new company - Swiggy
  README.md
  company-profiles/swiggy.md
Labels: addition, awaiting-checks

#1660 add new company - 3Blocks
  README.md
  company-profiles/3blocks.md
Labels: addition, awaiting-checks

#1661 Added a new company (SeatGeek)
  README.md
  company-profiles/seatgeek.md
Labels: addition, awaiting-checks

#1679 add new company - Deel
  README.md
  company-profiles/deel.md
Labels: addition

#1664 added company - Atento
  README.md
  company-profiles/atento.md
Labels: addition, awaiting-checks

#1666 Added new Company - Cosmic Chimps
  README.md
  company-profiles/cosmic-chimps.md
Labels: addition, awaiting-checks

#1669 add new company- Capgemini
  README.md
  company-profiles/capgemini.md
Labels: addition, awaiting-checks

#1678 added Exoscale
  README.md
  company-profiles/exoscale.md
Labels: addition, awaiting-checks

#1676 add company - RemoteMore
  README.md
  company-profiles/remotemore.md
Labels: addition, awaiting-checks

#1701 start the move to Jekyll and use Just the Docs
  .github/workflows/jekyll-gh-pages.yml
  Gemfile
  Gemfile.lock
  _config.yml
  index.md
Labels: enhancement

#1700 Add Inter.link company profile
  .github/CONTRIBUTING.md
  README.md
  company-profiles/inter-link.md
Labels: addition, housekeeping, Needs reviewing

#1703 Add new company - Namecheap
  README.md
  company-profiles/namecheap.md
Labels: addition, Needs reviewing

#1704 add new company - 90 Seconds
  README.md
  company-profiles/90-seconds.md
Labels: addition, Needs reviewing

#1697 add new company - Cognizant
  README.md
  company-profiles/cognizant.md
Labels: addition

#1721 Added New Company Fleetio
  README.md
  company-profiles/fleetio.md
Labels: addition, author-reply-needed, Needs reviewing

#1698 Added new Company 37signals
  README.md
  company-profiles/37signals.md
Labels: addition, author-reply-needed

#1706 Removed Featurist
  README.md
  company-profiles/featurist.md
Labels: housekeeping, Needs reviewing

#1724 add new company - Invesco
  README.md
  company-profiles/invesco.md
Labels: addition

#1694 add new company - Capmo
  README.md
  company-profiles/capmo.md
Labels: addition, author-reply-needed

#1731 add new company - Sonatype
  README.md
  company-profiles/sonatype.md
Labels: addition, awaiting-maintainer-approval

#1714 Add new company - JOOR
  README.md
  company-profiles/joor.md
Labels: addition

#1746 add new company - LOGROCKET
  README.md
  company-profiles/logrocket.md
Labels: addition, awating-review

#1691 Add new company: Renaissance
  README.md
  company-profiles/renaissance.md
Labels: addition, author-reply-needed

#1742 Edited Digitise
  README.md
  company-profiles/digitise.md
Labels: housekeeping, awating-review

#1729 add new company - Qatium
  README.md
  company-profiles/qatium.md
Labels: addition, author-reply-needed

#1750 Remove Donut App company
  README.md
  company-profiles/donut.md
Labels: housekeeping, awating-review

#1737 Added a new company - Greenstitch
  README.md
  company-profiles/greenstitch-io.md
Labels: addition, author-reply-needed

#1752 add new company - FDTE
  README.md
  company-profiles/fdte.md
Labels: addition

#1711 add new company - Willings Inc
  README.md
  company-profiles/willings-inc.md
Labels: addition, author-reply-needed

#1753 feat: add transfeera company
  README.md
  company-profiles/transfeera.md
Labels: addition

#1755 updated compucorp outdated links
  README.md
  company-profiles/compucorp.md
Labels: housekeeping

#1754 Added new remote company: Roadpass-Digital
  README.md
  company-profiles/roadpass-digital.md
Labels: addition, awaiting-checks
