Repository remoteintech/remote-jobs, pull requests merged in 2023-09, with the labels that each got.

#1646 Adding railscarma
  README.md
  company-profiles/railscarma.md
Labels: addition, awaiting-maintainer-approval

#1497 added company XWP
  README.md
  company-profiles/xwp.md
Labels: addition

#1607 add new company - Epsy Health
  README.md
  company-profiles/epsy-health.md
Labels: addition

#1608 edit abiturma company
  company-profiles/abiturma.md
Labels: housekeeping

#1609 Add new company - Zemoso
  README.md
  company-profiles/zemoso.md
Labels: addition, awaiting-maintainer-approval

#1612 Add new company - Primotly
  README.md
  company-profiles/primotly.md
Labels: addition, awaiting-maintainer-approval

#1613 Add new company - Mayven Studios
  README.md
  company-profiles/mayven-studios.md
Labels: addition, awaiting-maintainer-approval

#1532 Add BharatPe
  README.md
  company-profiles/bharatpe.md
Labels: addition

#1533 added Wipro company with its profile
  README.md
  company-profiles/wipro.md
Labels: addition, author-reply-needed

#1615 add new company - Doit
  README.md
  company-profiles/doit.md
Labels: addition

#1616 add new company - Svix
  README.md
  company-profiles/svix.md
Labels: addition

#1618 Add new company - Intent
  README.md
  company-profiles/intent.md
Labels: addition

#1620 add new company - Coforma
  README.md
  company-profiles/coforma.md
Labels: addition

#1626 Delete Brave Investments
  README.md
  company-profiles/brave-investments.md
Labels: removal, awaiting-maintainer-approval

#1627 edit Netris company
  README.md
  company-profiles/netris.md
Labels: housekeeping

#1630 Adding company Encora
  README.md
  company-profiles/encora.md
Labels: addition, awaiting-maintainer-approval

#1633 fix: website link (https://www.xapobank.com/)
  README.md
Labels: housekeeping, awaiting-maintainer-approval

#1635 added new company - Headforwards
  README.md
  company-profiles/headforwards.md
Labels: addition, awaiting-maintainer-approval

#1650 Add: Company Profile - Positiwise
  README.md
  company-profiles/positiwise.md
Labels: addition, awaiting-maintainer-approval

#1619 Rename real.digital to Kaufland ecommerce (and update figures)
  README.md
  company-profiles/kaufland-e-commerce.md
  company-profiles/real-digital.md
Labels: housekeeping, awaiting-checks
