Repository remoteintech/remote-jobs, pull requests merged in 2024-10, with the labels that each got.

#1857 Add New Company - Findem
  README.md
  company-profiles/findem.md
Labels: addition, awating-review

#1852 Add new company - WYEWORKS
  README.md
  company-profiles/wyeworks.md
Labels: awaiting-checks

#1838 Edit Syde company: update and rebrand (Hacktoberfest 2024)
  README.md
  company-profiles/inpsyde.md
  company-profiles/syde.md
Labels: awaiting-checks

#1806 [Bug] Fixes: #1802 Hanno "closed"
  README.md
  company-profiles/hanno.md
Labels: housekeeping, awating-review

#1851 Add Veeva Systems remote company
  README.md
  company-profiles/veeva.md
Labels: addition, awating-review

#1847 Add Klanik
  README.md
  company-profiles/klanik.md
Labels: addition, author-reply-needed

#1842 Remove Codestunts company (closes issue #1739) (Hacktoberfest 2024)
  README.md
  company-profiles/codestunts.md
Labels: housekeeping, awating-review

#1845 Edit Dropbox company (issue #1808) (Hacktoberfest 2024)
  README.md
  company-profiles/dropbox.md
Labels: housekeeping, awating-review

#1846 Edit Datadog company (issue #1808) (Hacktoberfest 2024)
  README.md
  company-profiles/datadog.md
Labels: housekeeping, awating-review

#1841 Updated the setupSearch function for #1736
  site/assets/companies-table.js
Labels: future-maybe, awaiting-checks, awating-review

#1831 add new company - SearchApi
  README.md
  company-profiles/searchapi.md
Labels: addition, awating-review

#1830 add new company - THD
  README.md
  company-profiles/the-home-depot.md
Labels: addition, awating-review

#1832 add new company - Zaneffi
  README.md
  company-profiles/zaneffi.md
Labels: addition, awating-review

#1829 add new company - Locus Robotics
  README.md
  company-profiles/locus-robotics.md
Labels: addition, awating-review

#1827 Added crazygames company
  README.md
  company-profiles/crazygames.md
Labels: addition, awating-review

#1765 added thrive company (Fixes#1784)
  README.md
  company-profiles/thrive-market.md
Labels: addition, rtm

#1766 added daktronics company (Fixes#1784)
  README.md
  company-profiles/daktronics.md
Labels: addition, awating-review

#1782 Add AAICO
  README.md
  company-profiles/applied-ai-company-aaico.md
Labels: addition, author-reply-needed

#1821 add new company - Code B Solutions
  README.md
  company-profiles/code-b-solutions.md
Labels: addition, awating-review

#1820 add new company - Aiir
  README.md
  company-profiles/aiir.md
Labels: addition, awating-review

#1813 Add new company - WireFuture
  README.md
  company-profiles/wirefuture.md
Labels: addition, awating-review

#1817 Edit Tide company
  company-profiles/tide.md
Labels: housekeeping, awating-review

#1807 Edit Fingerprint info
  README.md
  company-profiles/fingerprint.md
  company-profiles/fingerprintjs.md
Labels: housekeeping, awating-review

#1805 [Bug] Fixes: #1801 AirTreks "How to apply" link does not work correctly
  company-profiles/airtreks.md
Labels: housekeeping, awating-review

#1790 Added Schnell Solutions Limited company (Fixes #1789)
  README.md
  company-profiles/schnell-solutions-limited.md
Labels: addition
