Repository remoteintech/remote-jobs, pull requests merged in 2024-12, with the labels that each got.

#1828 Add new company - bilstein group
  README.md
  company-profiles/bilstein-group.md
Labels: addition, author-reply-needed

#1837 Added the Paypay Corporation for Hacktoberfest 2024.
  README.md
  company-profiles/paypay.md
Labels: addition, author-reply-needed, hacktoberfest-accepted

#1859 Remove 17hats company
  README.md
  company-profiles/17hats.md
Labels: housekeeping, hacktoberfest-accepted, awating-review

#1844 Added Akamai Technologies in Remote-Jobs Hacktoberfest 2024
  README.md
  company-profiles/akamai.md
Labels: addition, author-reply-needed, hacktoberfest-accepted

#1848 add new company - AtoZDebug
  README.md
  company-profiles/atozdebug.md
Labels: addition, author-reply-needed, hacktoberfest-accepted

#1860 Added Appen company
  README.md
  company-profiles/appen.md
Labels: addition, hacktoberfest-accepted, awating-review

#1866 Update turing.md
  company-profiles/turing.md
Labels: addition, hacktoberfest-accepted, awating-review

#1870 Improve URL handling for external links in index.js
  lib/index.js
Labels: hacktoberfest-accepted

#1871 Add new company - QuickTrials
  README.md
  company-profiles/quicktrials.md
Labels: hacktoberfest-accepted

#1872 Added Company Profile -> Redlio Designs
  README.md
  company-profiles/redlio-designs.md
Labels: hacktoberfest-accepted
