Repository remoteintech/remote-jobs, pull requests merged in 2025-07, with the labels that each got.

#1861 adding Meant4 company profile and updating README.md with Meant4 prof…
  README.md
  company-profiles/meant4.md
Labels: hacktoberfest-accepted, awaiting-maintainer-approval

#1891 Add new company - Ecosmic
  README.md
  company-profiles/ecosmic.md
Labels: addition, awating-review

#1893 [new company] - Nearform
  README.md
  company-profiles/nearform.md
Labels: addition, awating-review

#1904 Create CodingCops Company Profile and Update Readme file
  README.md
  company-profiles/codingcops.md
Labels: addition, awating-review

#1907 add new company - SCALOY
  README.md
  company-profiles/scaloy.md
Labels: addition, awating-review

#1918 Remove Celsius company
  README.md
  company-profiles/celsius.md
Labels: housekeeping

#1920 Add A-1 Auto Transport
  README.md
  company-profiles/a-1-auto-transport.md
Labels: addition, awating-review

#1917 [New Company] Rendr Software Group
  README.md
  company-profiles/rendr-software-group.md
Labels: addition, author-reply-needed

#1923 Search functionality updated for technology and region
  site/assets/companies-table.js
  site/assets/site.css
Labels: enhancement, awating-review

#1924 Add Moving Company
  README.md
  company-profiles/three-movers.md
Labels: addition, awating-review

#1926 Add new company - upcell
  README.md
  company-profiles/upcell.md
Labels: addition, awating-review

#1927 Add new company - Treez
  README.md
  company-profiles/treez.md
Labels: addition, awating-review

#1929 Adding Capital Placement Company
  README.md
  company-profiles/capital-placement.md
Labels: addition, awating-review

#1890 add new company - Zitadel
  README.md
  company-profiles/zitadel.md
Labels: addition, awaiting-maintainer-approval

#1952 fixes 1768
  README.md
  company-profiles/rechat.md
Labels: validation-passed
